name: "Docker"
description: "This action builds, and, pushes new Docker images."
inputs:
  username:
    description: "true"
    required: true
  password:
    description: "true"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chantzlarge/www:latest
