// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-nostr/nostr"
	"net/http"
)

// Injectors from wire.go:

func buildClientServer() *http.Server {
	handler := nostr.NewClient()
	server := &http.Server{
		Handler: handler,
	}
	return server
}
