// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-nostr/go-nostr/web"
)

// Injectors from wire.go:

func buildWebServer() *web.Server {
	server := web.NewServer()
	return server
}
