name: Angular
on:
  push:
jobs:
  web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install NPM dependencies
        working-directory: web/
        run: npm ci
      - name: Build Angular application
        working-directory: web/
        run: npm run build
      - name: Run Angular tests
        working-directory: web/
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: Run Angular linter
        working-directory: web/
        run: npm run lint
