name: Angular
on:
  push:
jobs:
  web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # TODO: add Angular build step
      # TODO: add Angular test step
      # TODO: add Angular lint step