name: Hugo
on:
  push:
jobs:
  hugo:
    name: Hugo
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install NPM dependencies
        run: npm ci
      - name: Build NPM packages
        run: npm run build -ws
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Build Hugo site
        run: hugo -s docs/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
