name: Hugo
on:
  push:
    branches:
      - main
jobs:
  docs:
    name: Docs
    environment: github-pages
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
      - name: Install NPM dependencies
        run: npm ci
      - name: Build NPM packages
        run: npm run build -ws
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Build Hugo site
        run: hugo -s ./docs/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./docs/public
      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v2
