name: Hugo
on:
  push:
    branches:
      - main
jobs:
  docs:
    name: Docs
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
      - name: Install NPM dependencies
        run: npm ci
      - name: Build NPM packages
        run: npm run build -ws
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Build Hugo site
        run: hugo -s internal/docs
      - name: Upload GitHub Pages artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: internal/docs/public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
