name: Hugo
on:
  push:
jobs:
  hugo:
    name: Hugo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # TODO: add NPM build step
      # TODO: add Hugo build step
      # TODO: add GitHub Pages publish step
